import './globals.css';
//
import Footer from '@/components/footer/page';
import Header from '@/components/header/page';
import { routes } from '@/routes/routes';
import { videoRoutes } from '@/routes/videoRoutes';
import Head from 'next/head';
//

export const metadata = {
    title: 'Báo Tuổi Trẻ Cloned',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <Head>
                <link
                    rel='icon'
                    href='/favicon.ico'
                />
                <link
                    rel='apple-touch-icon'
                    sizes='180x180'
                    href='/apple-touch-icon.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='32x32'
                    href='/favicon-32x32.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='16x16'
                    href='/favicon-16x16.png'
                />
                <link
                    rel='manifest'
                    href='/site.webmanifest'
                />
            </Head>
            <body className='overflow-x-hidden'>
                <Header
                    routes={routes}
                    videoRoutes={videoRoutes}
                />
                <main className='layoutContainer bg-white'>
                    <div className='main-container relative'>
                        <div className='leftBanner hidden sm:block'></div>
                        <div className='rightBanner hidden sm:block'></div>
                        {children}
                    </div>
                </main>
                <Footer />
            </body>
        </html>
    );
}
